FROM node:22.8.0-slim

RUN apt update && \
  apt install -y curl && \
  npm install -g nodemon

COPY start.sh /
RUN chmod +x /start.sh

# debian 
# RUN useradd -m -u 1000 guto - criar um usuario
# RUN usermod -u 1000 guto

# alpin3e
# RUN adduser -D -u 1000 guto - criar usuário
# RUN SED -I 'S/1000/1001/G' /etc/passwd 
USER node 

WORKDIR /home/node/app

#COPY package.json ./
#RUN npm install


EXPOSE 3000

#CMD ["tail", "-f", "/dev/null"]
CMD ["/start.sh"]
